### ISSUE TITLE
add --version flag to print out the version and exit

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/Isaac-XML-Validator#23]
for the python script specifically

**Comment by wofsauge** [comment]
its now printed when the tool is started to make it easier for docker users because they dont need to alter things

**Comment by Zamiell** [comment]
its not printed, this issue needs to be reopened

**Comment by Zamiell** [comment]
also, it should be a flag in addition to being printed every time, because if i want to just check the version and i dont want it to lint anything then the flag is useful

**Comment by wofsauge** [comment]
Arguments got added now
