### ISSUE TITLE
in default file path glob, ignore node_modules

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/Isaac-XML-Validator#24]
we need to ignore node_modules because end-users will get spurious errors for their deps otherwise when they simply run `isaac-xml-validator` with no other arguments

**Comment by Zamiell** [comment]
also, this would be a big performance optimization, because node_modules is huge and doesn't need to be parsed

**Comment by Zamiell** [comment]
now that i think on this more, maybe the correct behavior is to just ignore anything in .gitignore file, if present

**Comment by wofsauge** [comment]
can you fix this on your end? you can test this on your side better, because you have good test projects on hand

**Comment by Zamiell** [comment]
yeah ill take a look later tonight

**Comment by wofsauge** [comment]
ignore argument and .gitignore file support are added now
