### ISSUE TITLE
doesn't work in CI

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/Isaac-XML-Validator#27]
see this commit and the related ci output: https://github.com/Zamiell/racing-plus/commit/5417421fb415887af11f5968f292d7a316b093fd

**Comment by wofsauge** [comment]
Github action is fixed now. I dont know tho, what you mean in your error. The action you use didnt throw any errors and the log is clean as well...

**Comment by Zamiell** [comment]
to give more info:

the commit linked in the OP is a canary commit, where i intentionally introduce an error into the codebase, which should change CI from green --> red.
specifically, the error in question is removing the `anm2path` field in the `entities2.xml` file, which is a required field.

however, when you we look at the commit, it still has a green checkmark.
when we click on the green checkmark to inspect the CI run and see where things went wrong, we see that the `lint.sh` script runs, and it includes the following output:

```
Checking XML file: mod/content/costumes2.xml
Checking XML file: mod/content/entities2.xml
Checking XML file: mod/content/sounds.xml
```

so we can see that the entities2.xml file didn't generate any errors, which means that the python script doesn't work.

i can set up a test repo if you want to demonstrate the problem

**Comment by wofsauge** [comment]
![image](https://user-images.githubusercontent.com/245725/213924154-fd78cce9-9d88-402b-867e-15c457a316d1.png)
ive tested it locally now, and it works fine for me. maybe try to run the ci again with the newest version of the pip module

**Comment by wofsauge** [comment]
Bug inside the PyPI package is fixed now
