### ISSUE TITLE
variant auto-incrementation for pickups and effects should throw an error, since they are unsafe

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/Isaac-XML-Validator#28]
see https://github.com/Meowlala/RepentanceAPIIssueTracker/issues/436

**Comment by wofsauge** [comment]
I dont quite understand what you want me to change? Do you want, that the variant of an entity should be a required attribute?

**Comment by Zamiell** [comment]
> Do you want, that the variant of an entity should be a required attribute?

yes, but the tricky part is we only want the variant to be a required attribute when `id="5"` or `id="1000"`

**Comment by wofsauge** [comment]
Feature is added now. Will update pip module when the other issues are fixed as well
