### ISSUE TITLE
Support for ignore comment / ignore flag

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/Isaac-XML-Validator#31]
In my mod, I delete all cutscenes via editing "cutscenes.xml" and deleting all of the content in it. However, this causes `isaac-xml-validator` to fail. Thus, I need the ability to tell `isaac-xml-validator` to ignore this specific file.

I can think of two different ways to accomplish this, and I think the tool should support both of them to be as robust as possible.

## 1) `--ignore` Command Line Flag

`isaac-xml-validator` should support a `--ignore` command line flag, so that you could run it like this:

```
isaac-xml-validator --ignore cutscenes.xml
```

It should also support multiple values via splitting on commas. That would allow end-users to ignore multiple files like this:

```
isaac-xml-validator --ignore cutscenes.xml,entities2.xml
```

### 2) `isaac-xml-validator:disable` Comment

CSpell is a popular command-line program very similar to `isaac-xml-validator`. You run it on your repository, and it recursively looks through everything for spelling errors.

However, some files in a repository do not need to be spell checked, like log files. In these kinds of situations, you can bake in comments that cause the parser to skip the file like this:

```
<!-- cspell:disable -->
[rest of file content here]
```

Thus, I propose that `isaac-xml-validator` does the same thing:

```
<!-- isaac-xml-validator:disable -->
[rest of file content here]
```

A wrinkle here: XML parsing does not include comments AFAIK, so as a quick implementation the script can just look at the first line of the file to see if it has a matching disable comment.

**Comment by wofsauge** [comment]
ignore argument feature was added now
