### ISSUE TITLE
--ignore flag doesn't work

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/Isaac-XML-Validator#33]
See: https://github.com/Zamiell/racing-plus/actions/runs/4086934691/jobs/7046832174

**Comment by wofsauge** [comment]
This is fixed now. i had to disable the glob support for the ignore file string, though. sorry

**Comment by Zamiell** [comment]
Yeah, that's expected, because in bash the glob would get expanded before it ever hit any Python.
